# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=b'uploaded_photos'),
        ),
    ]
